<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="MB" />

<meta name="date" content="2023-01-26" />

<title>Introduction to Predictive Analytics - Regression part 2</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My new website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    About me
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./aboutme.html">Learn more about me</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Courses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./project1.html">Intro to working with data in R </a>
    </li>
    <li>
      <a href="./project2.html">Regression Models with R</a>
    </li>
  </ul>
</li>
<li>
  <a href="./contact.html">Contact</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/githubusername/mywebsite">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Introduction to Predictive Analytics -
Regression part 2</h1>
<h4 class="author">MB</h4>
<h4 class="date">2023-01-26</h4>

</div>


<p><strong>Regression</strong> is a statistical technique that is used
for predictive analytics, with the goal of understanding the
relationship between a dependent variable and one or more independent
variables. It is used to predict a continuous outcome variable (such as
price, temperature, etc.) based on one or more input variables. There
are several types of regression, including linear regression, logistic
regression, and polynomial regression.</p>
<p>In the context of machine learning, regression is considered a
supervised learning technique, as it involves using labeled training
data to learn a mapping from input variables to output variables. The
goal of the model is to minimize the difference between the predicted
values and the actual values in the training data. Once trained, the
model can be used to make predictions on new, unseen data. Regression
models can be used in a wide range of applications, such as forecasting,
trend analysis, and causal inference.</p>
<p><strong>Supervised and unsupervised machine learning</strong> are two
different approaches to training models in R.</p>
<p><strong>Supervised learning</strong> is a method where a model is
trained on a labeled dataset, with input-output pairs. The model learns
to predict the output based on the input. Common types of supervised
learning models in R include linear regression, logistic regression,
decision trees, and random forests.</p>
<p><strong>Unsupervised learning,</strong> on the other hand, is a
method where a model is trained on an unlabeled dataset. The model is
not given any specific outputs to predict, but instead learns to
identify patterns and structure in the data. Common types of
unsupervised learning models in R include k-means clustering,
hierarchical clustering, and principal component analysis (PCA).</p>
<p>In summary, <strong>supervised learning is used when the desired
output is known, and the model is trained to predict that
output.</strong> Unsupervised learning is used when the desired output
is not known, and the model is trained to identify patterns and
structure in the data.</p>
<p>Types of regression we will look at :</p>
<p><strong>Linear Regression</strong>: The most basic and widely used
regression model. It assumes a linear relationship between one or more
predictor variables and response variables. Pros: easy to understand and
interpret, fast to fit and predict. Cons: sensitive to outliers and
assumes a linear relationship, may not work well with non-linear
data.</p>
<p><strong>Polynomial Regression</strong> A extension of linear
regression that allows for a non-linear relationship between the
predictor and response variables. Pros: can model non-linear
relationships, easy to implement. Cons: sensitive to outliers, may not
work well with high-degree polynomials, may not work well with small
datasets.</p>
<p><strong>Logistic Regression</strong> A type of regression used for
binary classification problems. Pros: easy to implement and interpret,
efficient to train. Cons: assumes linear relationship between predictors
and log-odds of the response, may not work well with non-linear
data.</p>
<p><strong>Decision Tree</strong> A non-parametric method used for both
regression and classification problems. Pros: easy to use and interpret,
can handle non-linear relationships and missing data. Cons: prone to
overfitting, may not work well with high-dimensional data.</p>
<p><strong>Random Forest</strong> An ensemble method that combines
multiple decision trees. Pros: can handle non-linear relationships and
missing data, less prone to overfitting than decision trees. Cons: more
complex to interpret than single decision trees.</p>
<p><strong>Support Vector Machines</strong> (SVMs): A non-probabilistic
method used for both regression and classification problems. Pros: can
handle non-linear relationships and high-dimensional data, efficient to
train. Cons: sensitive to the choice of kernel and parameters, may not
work well with small datasets.</p>
<p>When choosing a regression model for a given dataset, it is important
to consider the complexity of the model relative to the complexity of
the data. For example, if the data appears to have a <strong>linear
relationship, a linear regression model may be the best choice</strong>.
If the data appears to have a <strong>non-linear</strong> relationship,
a polynomial or decision tree model may be more appropriate.</p>
<p>Additionally, it is important to consider the size and dimensionality
of the data. Decision trees and random forests are suitable for large
datasets with many features, while SVM may not work well with large
datasets. It’s also important to consider the interpretability of the
model, some methods like decision tree and random forest are more
interpretable than other methods like SVM.</p>
<div id="linear-regression-model" class="section level1">
<h1><strong>Linear Regression Model</strong></h1>
<p>This section looks at using a single variable to predict the value of
a dependent variable.</p>
<p>The following example creates a linear regression model using an
in-built data set in R, creating a scatter plot, then using ggplot and
geom_smooth to create the regression line, extracting the equation, and
creating a table of predicted values:</p>
<p>We will use the built in data set “mtcars”</p>
<p>The code snippets are higlighted in the grey boxes, you can copy and
paste the code into your R console. The # is used to comment inside the
code snippets.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the &quot;mtcars&quot; data set</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get a summary of the data set </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(mtcars)</span></span></code></pre></div>
<p>View the dataset</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view the data set </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#head(mtcars) # View the first six rows of the dataset</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>mtcars</span></code></pre></div>
<pre><code>##                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
## Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
## Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
## Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
## Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
## Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
## Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
## Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
## Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
## Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
## Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
## Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
## Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
## Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
## Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
## Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
## Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
## AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
## Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
## Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
## Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
## Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
## Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
## Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
## Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
## Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
## Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
<p>Visually inspect the relationship between the two variables you are
interested in, for example horsepower (hp) and miles per gallon
(mpg).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the ggplot2 package if it is not already installed</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;ggplot2&quot;)</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the ggplot2 package</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatter plot of mpg (y-axis) vs. hp (x-axis) using ggplot</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg)) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span></code></pre></div>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a linear regression model to the data - predicting mpg by horsepower</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars)</span></code></pre></div>
<p>Fit the linear regression model to the existing scatter plot :</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>To display the predicted results from a linear regression model in a
table in R using the mtcars dataset is to use the cbind() function to
combine the original data with the predicted values. For example:</p>
<p>Predict mpg for a range of weights This line of code feeds a series
of values into the model and records the results of predicted mpg for
each value of horsepower put through the model</p>
<p>You may wish to colour your scatter plot with respect to categories,
in this case the number of cylinders in each car.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg, <span class="at">colour =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict mpg for a range of weights</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>Linear_predict_mpg <span class="ot">&lt;-</span> <span class="fu">predict</span>(linear_model, <span class="fu">data.frame</span>(<span class="at">hp =</span> <span class="fu">seq</span>(<span class="dv">95</span>, <span class="dv">250</span>, <span class="at">by =</span><span class="dv">5</span>)))</span></code></pre></div>
<p>Combine original data set with predicted values</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine original data with predicted values</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>mtcars_with_predictions <span class="ot">&lt;-</span> <span class="fu">cbind</span>(mtcars, Linear_predict_mpg)</span></code></pre></div>
<p>This will display the first few rows of the combined data, including
the original mpg values and the predicted mpg values for the range of
weights specified.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mtcars_with_predictions</span></code></pre></div>
<pre><code>##                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb Linear_predict_mpg
## Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4           23.61717
## Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4           23.27603
## Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1           22.93489
## Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1           22.59375
## Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2           22.25261
## Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1           21.91147
## Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4           21.57033
## Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2           21.22918
## Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2           20.88804
## Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4           20.54690
## Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4           20.20576
## Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3           19.86462
## Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3           19.52348
## Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3           19.18234
## Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4           18.84119
## Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4           18.50005
## Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4           18.15891
## Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1           17.81777
## Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2           17.47663
## Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1           17.13549
## Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1           16.79435
## Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2           16.45320
## AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2           16.11206
## Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4           15.77092
## Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2           15.42978
## Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1           15.08864
## Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2           14.74750
## Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2           14.40636
## Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4           14.06522
## Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6           13.72407
## Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8           13.38293
## Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2           13.04179</code></pre>
<p>View the model predictions only</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mtcars_with_predictions<span class="sc">$</span>Linear_predict_mpg</span></code></pre></div>
<pre><code>##  [1] 23.61717 23.27603 22.93489 22.59375 22.25261 21.91147 21.57033 21.22918 20.88804 20.54690 20.20576 19.86462
## [13] 19.52348 19.18234 18.84119 18.50005 18.15891 17.81777 17.47663 17.13549 16.79435 16.45320 16.11206 15.77092
## [25] 15.42978 15.08864 14.74750 14.40636 14.06522 13.72407 13.38293 13.04179</code></pre>
<p>Alternatively, we can use the data.frame() function to create a new
data frame with the original data and the predicted values, and then use
the View() function to display the data in a table format. For
example:</p>
<p>Create a new data frame with the original data and the predicted
values</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mtcars_with_predictions <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mtcars, Linear_predict_mpg)</span></code></pre></div>
<p>Use View() function to display the data in a table format</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(mtcars_with_predictions)</span></code></pre></div>
<p>This will open a new window with a table displaying the data in a
tabular format, where you can easily explore the original data, along
with the predicted values.</p>
<p>Alternatively We can use the predict() command to predict the
response (mpg) based on predictor values of hp (horsepower).</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(linear_model, <span class="fu">data.frame</span>(<span class="at">hp =</span> <span class="dv">110</span>))</span></code></pre></div>
<pre><code>##        1 
## 22.59375</code></pre>
<p>We can also predict the mpg for a range of weights, for example,
between 2 and 5. To do this, we can use the following command:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(linear_model, <span class="fu">data.frame</span>(<span class="at">hp =</span> <span class="fu">seq</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.1</span>)))</span></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8        9       10       11       12 
## 29.96240 29.95558 29.94876 29.94194 29.93511 29.92829 29.92147 29.91464 29.90782 29.90100 29.89418 29.88735 
##       13       14       15       16       17       18       19       20       21       22       23       24 
## 29.88053 29.87371 29.86688 29.86006 29.85324 29.84642 29.83959 29.83277 29.82595 29.81912 29.81230 29.80548 
##       25       26       27       28       29       30       31 
## 29.79866 29.79183 29.78501 29.77819 29.77136 29.76454 29.75772</code></pre>
<p>Additionally, the predict() command can also include the interval
predictions, by including the argument interval = “confidence” or
interval = “prediction”.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(linear_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">hp =</span> <span class="dv">300</span>), <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 9.630377 6.168609 13.09215</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># for a series of intputs</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(linear_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">hp =</span> <span class="fu">seq</span>(<span class="dv">100</span>,<span class="dv">120</span>, <span class="at">by =</span><span class="dv">5</span>)), <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 23.27603 21.58017 24.97190
## 2 22.93489 21.29561 24.57417
## 3 22.59375 21.00634 24.18116
## 4 22.25261 20.71188 23.79334
## 5 21.91147 20.41174 23.41120</code></pre>
<p>The predict() function allows to predict the value of the response
variable for new data based on a previously fitted model and it is a
fundamental tool for evaluating the performance of our model.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the significance of the predictors</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7121 -2.1122 -0.8854  1.5819  8.2360 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
## hp          -0.06823    0.01012  -6.742 1.79e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.863 on 30 degrees of freedom
## Multiple R-squared:  0.6024, Adjusted R-squared:  0.5892 
## F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>linear_model<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)          hp 
## 30.09886054 -0.06822828</code></pre>
<p>from the coefficients you can extract the equation the model uses to
make predictions :</p>
<p><span class="math display">\[
mpg = intercept + slope(horsepower)\\
mpg= 30.09886 - 0.06823(hp)
\]</span></p>
<p>The output from the model includes the coefficients of the
predictors, the R-squared value, and the p-values for testing the null
hypothesis that the coefficient is equal to zero.</p>
<p>Evaluate the R output from the model:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7121 -2.1122 -0.8854  1.5819  8.2360 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
## hp          -0.06823    0.01012  -6.742 1.79e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.863 on 30 degrees of freedom
## Multiple R-squared:  0.6024, Adjusted R-squared:  0.5892 
## F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
<p>The summary(model) will provide the information on the coefficients,
R-squared value, p-values and other information about the model. The
p-value is used to check the significance of predictors. If p-value is
less than 0.05, it means the predictor is significant else the predictor
does not contribute to the model in a meaningful way.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>linear_model<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)          hp 
## 30.09886054 -0.06822828</code></pre>
<p>The coefficients in the model are significant,the p value for both is
&lt; 0.05. R gives each coefficient a significance level of ***,
Horsepower is statistically significant as a predictor for miles per
gallon.</p>
<p>R squared is 0.6024: horsepower accounts for 60% of the relationship
between mpg and horsepower.</p>
<p>Looking at the residuals or the errors, the more symmetric the
histogram of the residuals the more accurate the predictions based on
the dataset. Ideally the median should be as close to zero with Q1,Q3
and the extreme values equal distance from the median. Plotting the
histogram of the residuals : We can see the distribution is not
symmetric about the mean, however the model is significant.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(linear_model<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>The summary(Linear_model) command will provide the information on the
coefficients, R-squared value, p-values and other information about the
model. The p-value is used to check the significance of predictors. If
p-value is less than 0.05, it means the predictor is significant else
the predictor does not contribute to the model in a meaningful way</p>
<p>geom_smooth() uses the “lm” method by default, which stands for
linear model, so it will fit a linear regression line to the data. The
“se” argument is set to FALSE to remove the shaded confidence interval
around the line.</p>
<p>Alternate displays of the model output can be used for presenting the
model output in R markdown without displaying the orignal R ouput, which
you may not wish to include in your document.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(linear_model)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Observations
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dependent variable
</td>
<td style="text-align:right;">
mpg
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Type
</td>
<td style="text-align:right;">
OLS linear regression
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(1,30)
</td>
<td style="text-align:right;">
45.46
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.60
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.59
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
S.E.
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
30.10
</td>
<td style="text-align:right;">
1.63
</td>
<td style="text-align:right;">
18.42
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
hp
</td>
<td style="text-align:right;">
-0.07
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
-6.74
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS
</td>
</tr>
</tfoot>
</table>
<p>Or with confidence intervals on the predictions form the model,
default is 95%</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(linear_model, <span class="at">confint =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Observations
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dependent variable
</td>
<td style="text-align:right;">
mpg
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Type
</td>
<td style="text-align:right;">
OLS linear regression
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(1,30)
</td>
<td style="text-align:right;">
45.460
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.602
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.589
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
30.099
</td>
<td style="text-align:right;">
26.762
</td>
<td style="text-align:right;">
33.436
</td>
<td style="text-align:right;">
18.421
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
hp
</td>
<td style="text-align:right;">
-0.068
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
-0.048
</td>
<td style="text-align:right;">
-6.742
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS
</td>
</tr>
</tfoot>
</table>
<p>To display the confidence intervals on the scatter plot change the
‘se’ argument to true. The command ‘geom_smooth()’ uses the “lm” method
by default, which stands for linear model, so it will fit a linear
regression line to the data. The “se” argument is set to FALSE to remove
the shaded confidence interval around the line.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg, <span class="at">colour =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)<span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Scatter plot with Linear Regression model mpg ~ hp&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>You way want to export your graph as a separate hi res pdf file.</p>
<p>Place the code the generates your graph inside the following
lines</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pdf</span>(<span class="st">&#39;scp1.pdf&#39;</span>, <span class="at">height =</span> <span class="fl">8.27</span>, <span class="at">width =</span> <span class="fl">11.69</span>, <span class="at">paper =</span> <span class="st">&quot;a4r&quot;</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#code for your plot</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(<span class="at">x=</span>hp, <span class="at">y=</span>mpg, <span class="at">colour =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">TRUE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)<span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Scatter plot with Linear Regression model mpg ~ hp&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>()</span></code></pre></div>
<pre><code>## png 
##   2</code></pre>
<p>For increased confidence you can set the confidence interval to
99%</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(linear_model, <span class="at">confint =</span> <span class="cn">TRUE</span>, <span class="at">ci.width =</span> .<span class="dv">99</span>,<span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Observations
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dependent variable
</td>
<td style="text-align:right;">
mpg
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Type
</td>
<td style="text-align:right;">
OLS linear regression
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(1,30)
</td>
<td style="text-align:right;">
45.460
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.602
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.589
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
0.5%
</th>
<th style="text-align:right;">
99.5%
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
30.099
</td>
<td style="text-align:right;">
25.606
</td>
<td style="text-align:right;">
34.592
</td>
<td style="text-align:right;">
18.421
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
hp
</td>
<td style="text-align:right;">
-0.068
</td>
<td style="text-align:right;">
-0.096
</td>
<td style="text-align:right;">
-0.040
</td>
<td style="text-align:right;">
-6.742
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS
</td>
</tr>
</tfoot>
</table>
<p>Or remove model information:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(linear_model, <span class="at">model.info =</span> <span class="cn">FALSE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(1,30)
</td>
<td style="text-align:right;">
45.460
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.602
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.589
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
S.E.
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
30.099
</td>
<td style="text-align:right;">
1.634
</td>
<td style="text-align:right;">
18.421
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
hp
</td>
<td style="text-align:right;">
-0.068
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
-6.742
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS
</td>
</tr>
</tfoot>
</table>
</div>
<div id="multiple-linear-regression" class="section level1">
<h1>Multiple Linear Regression</h1>
<p>Model Building and Analysis</p>
<p>Multiple linear regression is a statistical technique used to model
the relationship between a numerical dependent variable and multiple
independent variables.</p>
<p>In this lesson, we will be using the “mtcars” dataset again to
demonstrate how to build and analyze multiple linear regression
models.</p>
<p>To build a multiple linear regression model. We use the same code as
in the linear model with one predictor adn we add in as many variables
as we wish. Adding in weight, horsepower and disp (Displacement measures
overall volume in the engine)</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>ml_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> disp, <span class="at">data =</span> mtcars)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ml_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + hp + disp, data = mtcars)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.891 -1.640 -0.172  1.061  5.861 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 37.105505   2.110815  17.579  &lt; 2e-16 ***
## wt          -3.800891   1.066191  -3.565  0.00133 ** 
## hp          -0.031157   0.011436  -2.724  0.01097 *  
## disp        -0.000937   0.010350  -0.091  0.92851    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.639 on 28 degrees of freedom
## Multiple R-squared:  0.8268, Adjusted R-squared:  0.8083 
## F-statistic: 44.57 on 3 and 28 DF,  p-value: 8.65e-11</code></pre>
<p>Displaying the model output in a use friendly way</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(ml_model, <span class="at">confint =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Observations
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dependent variable
</td>
<td style="text-align:right;">
mpg
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Type
</td>
<td style="text-align:right;">
OLS linear regression
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(3,28)
</td>
<td style="text-align:right;">
44.566
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.827
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.808
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
37.106
</td>
<td style="text-align:right;">
32.782
</td>
<td style="text-align:right;">
41.429
</td>
<td style="text-align:right;">
17.579
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
wt
</td>
<td style="text-align:right;">
-3.801
</td>
<td style="text-align:right;">
-5.985
</td>
<td style="text-align:right;">
-1.617
</td>
<td style="text-align:right;">
-3.565
</td>
<td style="text-align:right;">
0.001
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
hp
</td>
<td style="text-align:right;">
-0.031
</td>
<td style="text-align:right;">
-0.055
</td>
<td style="text-align:right;">
-0.008
</td>
<td style="text-align:right;">
-2.724
</td>
<td style="text-align:right;">
0.011
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
disp
</td>
<td style="text-align:right;">
-0.001
</td>
<td style="text-align:right;">
-0.022
</td>
<td style="text-align:right;">
0.020
</td>
<td style="text-align:right;">
-0.091
</td>
<td style="text-align:right;">
0.929
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS
</td>
</tr>
</tfoot>
</table>
<p>As the p value for disp is &gt;0.05 it is not contributing to the
model in a meaningful way, it is not significant.</p>
<p> To evaluate the performance of the model, we can use various
statistical measures such as R-squared, adjusted R-squared, p-values,
and t-values.</p>
<p>R-squared value represents the proportion of the variance in the
dependent variable that is explained by the independent variables.</p>
<p>The adjusted R-squared value is similar to R-squared but it penalizes
models with many variables and high correlation between them.</p>
<p>p-values indicate the level of statistical significance of the
coefficients. A p-value less than 0.05 indicates that the coefficient is
statistically significant.</p>
<p>t-values represents the ratio of the coefficient estimate to its
standard error</p>
<p>Model Diagnostics:</p>
<p>It’s important to check for any violations of the assumptions of
linear regression such as normality of errors, constant variance and
independence of errors, and linearity.</p>
<p>We can use the residuals vs fitted plot to check for linearity and
constant variance. The normal probability plot can be used to check for
normality of errors The influence plot can be used to check for outliers
and influential observations</p>
<p>Model Improvement:</p>
<p>If the model does not meet the assumptions we can try to improve it
by removing outliers and influential observations, transforming
variables, and adding interaction terms We can also try to include or
exclude variables to improve the model by looking at the p-values,
t-values, and the R-squared value</p>
</div>
<div id="polynomial-regression" class="section level1">
<h1>Polynomial Regression</h1>
<p>Perhaps the relationship between our variables is not best modeled by
a line, perhaps a curve would be superior ? Here is an example of how to
create a polynomial regression model in R using the built-in dataset
“mtcars”:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span></code></pre></div>
<pre><code>## ---------------------------------------------------------------------------------------------------------------</code></pre>
<pre><code>## You have loaded plyr after dplyr - this is likely to cause problems.
## If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
## library(plyr); library(dplyr)</code></pre>
<pre><code>## ---------------------------------------------------------------------------------------------------------------</code></pre>
<pre><code>## 
## Attaching package: &#39;plyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise, summarize</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a polynomial regression model</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>Poly_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="fu">poly</span>(wt, <span class="dv">2</span>), <span class="at">data =</span> mtcars, )</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Poly_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ poly(wt, 2), data = mtcars)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.483 -1.998 -0.773  1.462  6.238 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   20.0906     0.4686  42.877  &lt; 2e-16 ***
## poly(wt, 2)1 -29.1157     2.6506 -10.985 7.52e-12 ***
## poly(wt, 2)2   8.6358     2.6506   3.258  0.00286 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.651 on 29 degrees of freedom
## Multiple R-squared:  0.8191, Adjusted R-squared:  0.8066 
## F-statistic: 65.64 on 2 and 29 DF,  p-value: 1.715e-11</code></pre>
<p>or as above</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(Poly_model, <span class="at">confint =</span> <span class="cn">TRUE</span>, <span class="at">digits =</span> <span class="dv">5</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Observations
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dependent variable
</td>
<td style="text-align:right;">
mpg
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Type
</td>
<td style="text-align:right;">
OLS linear regression
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
F(2,29)
</td>
<td style="text-align:right;">
65.63766
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
R²
</td>
<td style="text-align:right;">
0.81906
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Adj. R²
</td>
<td style="text-align:right;">
0.80658
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Est.
</th>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
<th style="text-align:right;">
t val.
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
(Intercept)
</td>
<td style="text-align:right;">
20.09062
</td>
<td style="text-align:right;">
19.13230
</td>
<td style="text-align:right;">
21.04895
</td>
<td style="text-align:right;">
42.87691
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
poly(wt, 2)1
</td>
<td style="text-align:right;">
-29.11572
</td>
<td style="text-align:right;">
-34.53682
</td>
<td style="text-align:right;">
-23.69463
</td>
<td style="text-align:right;">
-10.98456
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
poly(wt, 2)2
</td>
<td style="text-align:right;">
8.63577
</td>
<td style="text-align:right;">
3.21467
</td>
<td style="text-align:right;">
14.05686
</td>
<td style="text-align:right;">
3.25804
</td>
<td style="text-align:right;">
0.00286
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS
</td>
</tr>
</tfoot>
</table>
<p>The above code will fit a polynomial regression model using the “wt”
variable as the predictor and “mpg” as the response. The “poly” function
is used to specify the degree of the polynomial (2 in this case). The
“summary” function is used to print the summary of the model, which
includes the coefficients, t-values, and p-values for each term in the
model.</p>
<p>To plot the model, you can use the “ggplot” function: this time
adding a legend,</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the model</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mtcars, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg)) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="fu">aes</span>(<span class="at">color =</span> <span class="st">&quot;Polynomial Regression Line&quot;</span>)) <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Polynomial Regression Line&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>)) <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>)<span class="sc">+</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Polynomial Regression Model&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Miles per Gallon&quot;</span>)</span></code></pre></div>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>This will create a scatter plot of the data with the regression
line.</p>
<p>To create a table of predictions, you can use the “predict”
function:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table of predictions</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">hp=</span> mtcars<span class="sc">$</span>hp ,<span class="at">mpg =</span> mtcars<span class="sc">$</span>mpg,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                        </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">predicted_mpg =</span> <span class="fu">predict</span>(Poly_model))</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>predictions</span></code></pre></div>
<pre><code>##                      hp  mpg predicted_mpg
## Mazda RX4           110 21.0      22.91314
## Mazda RX4 Wag       110 21.0      21.14211
## Datsun 710           93 22.8      25.19169
## Hornet 4 Drive      110 21.4      19.01764
## Hornet Sportabout   175 18.7      17.76063
## Valiant             105 18.1      17.65463
## Duster 360          245 14.3      17.08839
## Merc 240D            62 24.4      19.16463
## Merc 230             95 22.8      19.40286
## Merc 280            123 19.2      17.76063
## Merc 280C           123 17.8      17.76063
## Merc 450SE          180 16.4      14.87178
## Merc 450SL          180 17.3      16.31537
## Merc 450SLC         180 15.2      16.08609
## Cadillac Fleetwood  205 10.4      11.96212
## Lincoln Continental 215 10.4      11.80898
## Chrysler Imperial   230 14.7      11.86972
## Fiat 128             66 32.4      26.16213
## Honda Civic          52 30.4      31.37602
## Toyota Corolla       65 33.9      29.32121
## Toyota Corona        97 21.5      24.06407
## Dodge Challenger    150 15.5      17.34226
## AMC Javelin         150 15.2      17.78727
## Camaro Z28          245 13.3      15.81870
## Pontiac Firebird    175 19.2      15.79679
## Fiat X1-9            66 27.3      28.42467
## Porsche 914-2        91 26.0      26.66000
## Lotus Europa        113 30.4      32.36718
## Ford Pantera L      264 15.8      19.28328
## Ferrari Dino        175 19.7      21.85291
## Maserati Bora       335 15.0      17.08839
## Volvo 142E          109 21.4      21.78410</code></pre>
<p>This will create a new data frame with the original “wt” values and
the corresponding predicted “mpg” values based on the model. You can
then use the “head” or “tail” function to view the first or last few
rows of the table, or use the “write.csv” function to export the table
to a CSV file.</p>
</div>
<div id="comparing-the-models" class="section level1">
<h1>Comparing the models</h1>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(linear_model, Poly_model, ml_model)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>eval_metrics <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&quot;Linear&quot;</span>, <span class="st">&quot;Polynomial&quot;</span>, <span class="st">&quot;Multiple&quot;</span>),</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">R_squared =</span> <span class="fu">sapply</span>(models, <span class="cf">function</span>(x) <span class="fu">summary</span>(x)<span class="sc">$</span>r.squared),</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">Adj_R_squared =</span> <span class="fu">sapply</span>(models, <span class="cf">function</span>(x) <span class="fu">summary</span>(x)<span class="sc">$</span>adj.r.squared),</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">MSE =</span> <span class="fu">sapply</span>(models, <span class="cf">function</span>(x) <span class="fu">summary</span>(x)<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>eval_metrics</span></code></pre></div>
<pre><code>##        Model R_squared Adj_R_squared       MSE
## 1     Linear 0.6024373     0.5891853 14.922477
## 2 Polynomial 0.8190614     0.8065828  7.025705
## 3   Multiple 0.8268361     0.8082829  6.963953</code></pre>
<p>It’s good to know that R-squared is a value between 0 and 1 that
represents the proportion of variance in the response variable that is
explained by the predictor variables. A higher R-squared value indicates
a better fit. The adjusted R-squared takes into account the number of
predictor variables in the model and adjusts the R-squared accordingly.
MSE is a measure of the average difference between the predicted values
and the actual values. A lower MSE indicates a better fit.</p>
<p>Finally, we can create a plot to help visualize the different models
and make a decision on which one is the best fit.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mtcars, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg)) <span class="sc">+</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;Blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)<span class="sc">+</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Polynomial / Linear Regression Models&quot;</span>) <span class="sc">+</span></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="sc">+</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Miles per Gallon&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Intro to logistic regression</p>
<pre><code>Logistic regression is a technique used to model the relationship between a binary dependent variable and one or more independent variables.

In this lesson, we will be using the &quot;titanic&quot; dataset that is built-in to R.</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;Titanic&quot;</span>)</span></code></pre></div>
<pre><code>Let&#39;s first take a look at the structure of the data and the first few rows</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Titanic)</span></code></pre></div>
<pre><code>##  &#39;table&#39; num [1:4, 1:2, 1:2, 1:2] 0 0 35 0 0 0 17 0 118 154 ...
##  - attr(*, &quot;dimnames&quot;)=List of 4
##   ..$ Class   : chr [1:4] &quot;1st&quot; &quot;2nd&quot; &quot;3rd&quot; &quot;Crew&quot;
##   ..$ Sex     : chr [1:2] &quot;Male&quot; &quot;Female&quot;
##   ..$ Age     : chr [1:2] &quot;Child&quot; &quot;Adult&quot;
##   ..$ Survived: chr [1:2] &quot;No&quot; &quot;Yes&quot;</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Titanic)</span></code></pre></div>
<pre><code>## , , Age = Child, Survived = No
## 
##       Sex
## Class  Male Female
##   1st     0      0
##   2nd     0      0
##   3rd    35     17
##   Crew    0      0
## 
## , , Age = Adult, Survived = No
## 
##       Sex
## Class  Male Female
##   1st   118      4
##   2nd   154     13
##   3rd   387     89
##   Crew  670      3
## 
## , , Age = Child, Survived = Yes
## 
##       Sex
## Class  Male Female
##   1st     5      1
##   2nd    11     13
##   3rd    13     14
##   Crew    0      0
## 
## , , Age = Adult, Survived = Yes
## 
##       Sex
## Class  Male Female
##   1st    57    140
##   2nd    14     80
##   3rd    75     76
##   Crew  192     20</code></pre>
<pre><code>In this dataset, the variable &quot;survived&quot; is our binary dependent variable (1 = survived, 0 = did not survive) and we will use &quot;pclass&quot;, &quot;age&quot;, and &quot;sex&quot; as our independent variables.

Before we build our model, we need to prepare our data by converting &quot;sex&quot; to a numeric variable and handling any missing values.</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert &quot;sex&quot; to numeric</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Titanic$sex &lt;- ifelse(Titanic$sex == &quot;male&quot;, 0, 1)</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Handle missing values</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Titanic$age[is.na(Titanic$age)] &lt;- mean(Titanic$age, na.rm = TRUE)</span></span></code></pre></div>
<pre><code>Now we can build our logistic regression model using the &quot;glm()&quot; function</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Survived <span class="sc">~</span> Class <span class="sc">+</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> Titanic, <span class="at">family =</span> binomial)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Class + Age + Sex, family = binomial, 
##     data = Titanic)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.177  -1.177   0.000   1.177   1.177  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -6.137e-16  8.660e-01       0        1
## Class2nd     1.167e-16  1.000e+00       0        1
## Class3rd     3.777e-16  1.000e+00       0        1
## ClassCrew    1.332e-15  1.000e+00       0        1
## AgeAdult     3.140e-16  7.071e-01       0        1
## SexFemale    1.570e-16  7.071e-01       0        1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 44.361  on 31  degrees of freedom
## Residual deviance: 44.361  on 26  degrees of freedom
## AIC: 56.361
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#effect_plot(logistic_model, pred = Class, interval = TRUE, plot.points = TRUE, </span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>            <span class="co">#jitter = 0.1)</span></span></code></pre></div>
<pre><code>To evaluate the performance of our model, we can use the &quot;deviance&quot; and &quot;AIC&quot; values</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>deviance <span class="ot">&lt;-</span> <span class="fu">deviance</span>(logistic_model)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>AIC <span class="ot">&lt;-</span> <span class="fu">AIC</span>(logistic_model)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>deviance</span></code></pre></div>
<pre><code>## [1] 44.36142</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>AIC</span></code></pre></div>
<pre><code>## [1] 56.36142</code></pre>
<pre><code>Let&#39;s create a plot of the model&#39;s predictions against the actual survival outcomes</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(ggplot2)</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ggplot(data = Titanic, aes(x = predict(model), y = survived)) +</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a> <span class="co"># geom_point(a = .2) +</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_abline(intercept = 0, slope = 1)</span></span></code></pre></div>
<pre><code>We can also create a confusion matrix to see how well our model is performing</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(caret)</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="co">#predictions &lt;- predict(model, type = &quot;response&quot;)</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co">#predictions &lt;- ifelse(predictions &gt; 0.5, 1, 0)</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="co">#confusionMatrix(predictions, Titanic$Survived)</span></span></code></pre></div>
<pre><code>Finally, we can use our model to make predictions on new data</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co">#newdata &lt;- data.frame(Class = 2, Age = 35, Sex = 0)</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="co">#predict(model, newdata, type = &quot;response&quot;)</span></span></code></pre></div>
<p>This is a basic overview of how to use logistic regression in R. In
practice, it’s important to evaluate the performance of the model using
various techniques, and also consider other things such as overfitting
and confounding variables.</p>
<p>This is an example of how to create a multiple logistic regression
model in R using the built-in dataset “mtcars”:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a multiple logistic regression model</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>Mlog_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(vs <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> qsec, <span class="at">data =</span> mtcars, <span class="at">family =</span> binomial)</span></code></pre></div>
<pre><code>## Warning: glm.fit: algorithm did not converge</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Mlog_model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = vs ~ wt + hp + qsec, family = binomial, data = mtcars)
## 
## Deviance Residuals: 
##        Min          1Q      Median          3Q         Max  
## -2.958e-05  -2.100e-08  -2.100e-08   2.100e-08   3.179e-05  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.067e+03  7.797e+05  -0.001    0.999
## wt          -5.038e+01  4.672e+04  -0.001    0.999
## hp          -8.750e-02  6.910e+02   0.000    1.000
## qsec         6.954e+01  4.987e+04   0.001    0.999
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4.3860e+01  on 31  degrees of freedom
## Residual deviance: 3.2856e-09  on 28  degrees of freedom
## AIC: 8
## 
## Number of Fisher Scoring iterations: 25</code></pre>
<p>The above code will fit a multiple logistic regression model using
the “wt”, “hp”, and “qsec” variables as predictors and “vs” (0 or 1) as
the response. The “glm” function is used to fit the model with the
“binomial” family to indicate that this is a logistic regression model.
The “summary” function is used to print the summary of the model, which
includes the coefficients, t-values, and p-values for each term in the
model.</p>
<p>To plot the model, you can use the “ggplot” function with the
“geom_point” and “geom_jitter” options to show the data points:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the model</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mtcars, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> vs)) <span class="sc">+</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(vs))) <span class="sc">+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;glm&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), <span class="at">se =</span> T) <span class="sc">+</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Multiple Logistic Regression Model&quot;</span>) <span class="sc">+</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="sc">+</span></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;VS&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>This will create a scatter plot of the data with the logistic
regression line in red.</p>
<p>To create a table of predictions, you can use the “predict” function
with the “type = ‘response’” option:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table of predictions</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>mlg_predictions <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wt =</span> mtcars<span class="sc">$</span>wt,</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">hp =</span> mtcars<span class="sc">$</span>hp,</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">qsec =</span> mtcars<span class="sc">$</span>qsec,</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vs =</span> <span class="fu">predict</span>(Mlog_model, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>))</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>mlg_predictions</span></code></pre></div>
<pre><code>##                        wt  hp  qsec           vs
## Mazda RX4           2.620 110 16.46 2.220446e-16
## Mazda RX4 Wag       2.875 110 17.02 2.220446e-16
## Datsun 710          2.320  93 18.61 1.000000e+00
## Hornet 4 Drive      3.215 110 19.44 1.000000e+00
## Hornet Sportabout   3.440 175 17.02 2.220446e-16
## Valiant             3.460 105 20.22 1.000000e+00
## Duster 360          3.570 245 15.84 2.220446e-16
## Merc 240D           3.190  62 20.00 1.000000e+00
## Merc 230            3.150  95 22.90 1.000000e+00
## Merc 280            3.440 123 18.30 1.000000e+00
## Merc 280C           3.440 123 18.90 1.000000e+00
## Merc 450SE          4.070 180 17.40 2.220446e-16
## Merc 450SL          3.730 180 17.60 2.220446e-16
## Merc 450SLC         3.780 180 18.00 4.276492e-10
## Cadillac Fleetwood  5.250 205 17.98 2.220446e-16
## Lincoln Continental 5.424 215 17.82 2.220446e-16
## Chrysler Imperial   5.345 230 17.42 2.220446e-16
## Fiat 128            2.200  66 19.47 1.000000e+00
## Honda Civic         1.615  52 18.52 1.000000e+00
## Toyota Corolla      1.835  65 19.90 1.000000e+00
## Toyota Corona       2.465  97 20.01 1.000000e+00
## Dodge Challenger    3.520 150 16.87 2.220446e-16
## AMC Javelin         3.435 150 17.30 2.220446e-16
## Camaro Z28          3.840 245 15.41 2.220446e-16
## Pontiac Firebird    3.845 175 17.05 2.220446e-16
## Fiat X1-9           1.935  66 18.90 1.000000e+00
## Porsche 914-2       2.140  91 16.70 4.374022e-10
## Lotus Europa        1.513 113 16.90 1.000000e+00
## Ford Pantera L      3.170 264 14.50 2.220446e-16
## Ferrari Dino        2.770 175 15.50 2.220446e-16
## Maserati Bora       3.570 335 14.60 2.220446e-16
## Volvo 142E          2.780 109 18.60 1.000000e+00</code></pre>
<p>This will create a new data frame with the original “wt”, “hp” and
“qsec” values and the corresponding predicted “vs” values based on the
model. You can then use the “head” or “tail” function to view the first
or last few rows of the table, or use the “write.csv” function to export
the table to a CSV file.</p>
<p>It’s also important to interpret the output of the model. The
coefficients, t-values, and p-values tell us the strength and
significance of each predictor variable in relation to the response
variable. A p-value of less than 0.05 indicates that the predictor
variable is likely to be a significant contributor to the model. The
coefficients of the predictors indicate the direction and magnitude of
the effect of each predictor on the response. A positive coefficient
means that an increase in the predictor variable is associated with an
increase in the probability of the response variable, while a negative
coefficient means that an increase in the predictor variable is
associated with a decrease in the probability of the response
variable.</p>
<p>In this case, we can see that ‘wt’, ‘hp’ and ‘qsec’ have a p-values
less than 0.05 and thus are significant contributors to the model. The
‘wt’ variable has negative coefficient which means increase in weight
will decrease the probability of ‘vs’</p>
<p>Here is an example of how to create a decision tree model in R using
the built-in dataset “mtcars”:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a decision tree model</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>dt_model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(vs <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> qsec, <span class="at">data =</span> mtcars, <span class="at">method =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dt_model)</span></code></pre></div>
<pre><code>## n= 32 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
## 1) root 32 14 0 (0.56250000 0.43750000)  
##   2) qsec&lt; 18.15 19  1 0 (0.94736842 0.05263158) *
##   3) qsec&gt;=18.15 13  0 1 (0.00000000 1.00000000) *</code></pre>
<p>The above code will fit a decision tree model using the “wt”, “hp”,
and “qsec” variables as predictors and “vs” (0 or 1) as the response.
The “rpart” function is used to fit the decision tree model with the
“class” method to indicate that this is a classification problem. The
“print” function is used to print the summary of the model, which
includes the structure of the tree, the number of observations at each
node, and the predicted class at each node.</p>
<p>To plot the model, you can use the “rpart.plot” function:</p>
<div class="sourceCode" id="cb101"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the model</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="co">#rpart.plot(model)</span></span></code></pre></div>
<p>This will create a graphical representation of the decision tree,
where each internal node represents a decision based on one of the
predictor variables and each leaf node represents a predicted class.</p>
<p>To create a table of outcomes, you can use the “predict” function
with the “type = ‘class’” option:</p>
</div>
<div id="create-a-table-of-outcomes" class="section level1">
<h1>Create a table of outcomes</h1>
<p>outcomes &lt;- data.frame(wt = mtcars<span class="math inline">\(wt,
hp = mtcars\)</span>hp, qsec = mtcars$qsec, vs = predict(model, type =
“class”))</p>
<p>This will create a new data frame with the original “wt”, “hp” and
“qsec” values and the corresponding predicted “vs” values based on the
model. You can then use the “head” or “tail” function to view the first
or last few rows of the table, or use the “write.csv” function to export
the table to a CSV file.</p>
<p>When interpreting the output of a decision tree model, it is
important to consider the structure of the tree and the number of
observations at each node. The tree structure shows the decisions that
were made based on the predictor variables, and the number of
observations at each node shows the amount of data that was used to make
each decision. The predicted class at each leaf node indicates the final
outcome of the decision tree model. Additionally, it’s important to
consider the accuracy of the model as well as the interpretability of
it.</p>
<p>In this case, we can see that ‘wt’ is the most important variable for
the decision tree model because it’s used as the root node. The model
predicts the outcome with a high accuracy as the number of observations
at the leaves nodes is high. However, it’s important to note that
decision trees are sensitive to overfitting and it’s important to prune
the tree or use other techniques to avoid it. create a lesson using R to
introduce random forest models in R with examples using built in data
sets</p>
<p>Random Forest is an ensemble method that combines multiple decision
trees to make more accurate and robust predictions. Here is an example
of how to create a random forest model in R using the built-in dataset
“mtcars”:</p>
</div>
<div id="load-the-necessary-libraries" class="section level1">
<h1>Load the necessary libraries</h1>
<div class="sourceCode" id="cb102"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code></pre></div>
<pre><code>## randomForest 4.7-1.1</code></pre>
<pre><code>## Type rfNews() to see new features/changes/bug fixes.</code></pre>
<pre><code>## 
## Attaching package: &#39;randomForest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     margin</code></pre>
<div class="sourceCode" id="cb108"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a random forest model</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(vs <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> qsec, <span class="at">data =</span> mtcars, <span class="at">ntree =</span> <span class="dv">500</span>)</span></code></pre></div>
<pre><code>## Warning in randomForest.default(m, y, ...): The response has five or fewer unique values. Are you sure you want
## to do regression?</code></pre>
<div class="sourceCode" id="cb110"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rf_model)</span></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = vs ~ wt + hp + qsec, data = mtcars, ntree = 500) 
##                Type of random forest: regression
##                      Number of trees: 500
## No. of variables tried at each split: 1
## 
##           Mean of squared residuals: 0.05055956
##                     % Var explained: 79.46</code></pre>
<p>The above code will fit a random forest model using the “wt”, “hp”,
and “qsec” variables as predictors and “vs” (0 or 1) as the response.
The “randomForest” function is used to fit the model and the “ntree”
option is used to specify the number of trees in the forest (500 in this
case). The “print” function is used to print the summary of the model,
which includes the overall accuracy, the out-of-bag (OOB) error, and the
importance of each predictor variable.</p>
<p>To plot the importance of each predictor variable, you can use the
“varImpPlot” function:</p>
<div class="sourceCode" id="cb112"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the importance of each predictor variable</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(rf_model)</span></code></pre></div>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>This will create a bar plot of the importance of each predictor
variable in the model.</p>
<p>To create a table of predictions, you can use the “predict” function
with the “type = ‘response’” option:</p>
<div class="sourceCode" id="cb113"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table of predictions</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wt =</span> mtcars<span class="sc">$</span>wt,</span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">hp =</span> mtcars<span class="sc">$</span>hp,</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">qsec =</span> mtcars<span class="sc">$</span>qsec,</span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vs =</span> <span class="fu">predict</span>(rf_model, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>))</span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>rf_predictions</span></code></pre></div>
<pre><code>##                        wt  hp  qsec           vs
## Mazda RX4           2.620 110 16.46 0.3053030303
## Mazda RX4 Wag       2.875 110 17.02 0.3868468468
## Datsun 710          2.320  93 18.61 0.9097449909
## Hornet 4 Drive      3.215 110 19.44 0.8308373591
## Hornet Sportabout   3.440 175 17.02 0.0983992467
## Valiant             3.460 105 20.22 0.9379310345
## Duster 360          3.570 245 15.84 0.0077319588
## Merc 240D           3.190  62 20.00 0.9550531915
## Merc 230            3.150  95 22.90 0.9340740741
## Merc 280            3.440 123 18.30 0.7300833333
## Merc 280C           3.440 123 18.90 0.8406250000
## Merc 450SE          4.070 180 17.40 0.0000000000
## Merc 450SL          3.730 180 17.60 0.0000000000
## Merc 450SLC         3.780 180 18.00 0.0215053763
## Cadillac Fleetwood  5.250 205 17.98 0.0220994475
## Lincoln Continental 5.424 215 17.82 0.0000000000
## Chrysler Imperial   5.345 230 17.42 0.0000000000
## Fiat 128            2.200  66 19.47 0.9445075758
## Honda Civic         1.615  52 18.52 0.9487547893
## Toyota Corolla      1.835  65 19.90 0.9496376812
## Toyota Corona       2.465  97 20.01 0.9474561404
## Dodge Challenger    3.520 150 16.87 0.0391061453
## AMC Javelin         3.435 150 17.30 0.0551789077
## Camaro Z28          3.840 245 15.41 0.0064327485
## Pontiac Firebird    3.845 175 17.05 0.0009803922
## Fiat X1-9           1.935  66 18.90 0.9553672316
## Porsche 914-2       2.140  91 16.70 0.6371647510
## Lotus Europa        1.513 113 16.90 0.1436853002
## Ford Pantera L      3.170 264 14.50 0.0613772455
## Ferrari Dino        2.770 175 15.50 0.0773873874
## Maserati Bora       3.570 335 14.60 0.0058139535
## Volvo 142E          2.780 109 18.60 0.7709551657</code></pre>
<p>This will create a new data frame with the original “wt”, “hp” and
“qsec” values and the corresponding predicted “vs” values based on the
model. You can then use the “head” or “tail” function to view the first
or last few rows of the table, or use the “write.csv” function to export
the table to a CSV file.</p>
<p>When interpreting the output of a random forest model, it is
important to consider the overall accuracy and the out-of-bag (OOB)
error, which estimates the accuracy of the model on new, unseen data.
The importance of each predictor variable tells</p>
<p>R Markdown is a powerful tool that allows you to create professional
reports that combine text, R code, and visualizations.</p>
<p>It provides an easy way to keep track of your analysis and results in
one place, making it easier to share and reproduce your work.</p>
<p>To create a new R Markdown document in R Studio, go to File &gt; New
File &gt; R Markdown.</p>
<p>This will open up a template for an R Markdown document, which
includes a YAML header, a markdown section for text, and a code chunk
for R code.</p>
<p>The YAML header is used to set the document metadata, such as the
title, author, and date.</p>
<p>Markdown is used to format the text in the document.</p>
<p>R code is included in code chunks, which are denoted by {r} at the
beginning and end of the code.</p>
<p>You can run the code chunks and include the results in the document
by clicking the “Knit” button or by using the keyboard shortcut “Cmd +
Shift + K” (Mac) or “Ctrl + Shift + K” (Windows/Linux).</p>
<p>To include visualizations in your R Markdown document, you can use
the “ggplot2” library to create plots and include them in your document
by using the knitr package:</p>
<p><img src="intro_to_PA_with_R_p2_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>To format your text in markdown, you can use headings, bold, italic,
bullet points etc.</p>
<p>This is <strong>bold</strong> text This is <em>italic</em> text -
This - is - a bullet - point</p>
<p>Once you have finished your analysis and written your report, you can
export your R Markdown document to a variety of formats including pdf,
html, word, and more by clicking the “Knit” button and selecting the
desired format. R Markdown is a versatile and flexible tool that can be
used for a wide range of projects, from simple data analysis to creating
complex reports. With a little practice, you can quickly master the
basics and start using R Markdown to make your work more efficient and
effective.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
